# GISS Practical Week 7: Spatial Autocorrelation

### Analysing Spatial Autocorrelation with Moran’s I, LISA and friends

*Question: Are the values (in this case the density of blue plaques) similar (or dissimilar) across the wards of London?*

Step 1: Load libraries and data

Download 'LondonWardData' from the London Data Store: https://data.london.gov.uk/dataset/statistical-gis-boundary-files-london

Dowload 'Blue Plaque' data from: https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson

```{r}
library(janitor)
library(sf)
library(tidyverse)
library(here)
library(tmap)

#read in data
LondonWards <- st_read(here("statistical-gis-boundaries-london/ESRI/London_Ward.shp"))

LondonWardsMerged <- st_read(here("statistical-gis-boundaries-london/ESRI/London_Ward_CityMerged.shp")) %>% 
  st_transform(., 27700)

WardData <- read_csv("https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv", 
                     locale = locale(encoding = "latin1"), 
                     na = c("NA", "n/a")) %>% 
  clean_names()

BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson") %>% 
  st_transform(., 27700)

#join WardData with the Merged Ward Data
LondonWardsMerged <- LondonWardsMerged %>% 
  left_join(WardData,
            by = c("GSS_CODE" = "new_code")) %>% 
  dplyr::distinct(GSS_CODE, .keep_all = T) %>% 
  dplyr::select(GSS_CODE, ward_name, average_gcse_capped_point_scores_2014)


```


Plot data on the map

```{r}
tm_shape(LondonWardsMerged) +
  tm_polygons(alpha = 0.5, border.col = "black") +
  tm_shape(BluePlaques) +
  tm_dots(col = "blue") +
  tm_layout(frame = FALSE)
```

